ResNet50_API/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resnet50.urls'))
]

ResNet50_App/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resnet50.urls'))
]

urlpatterns += staticfiles_urlpatterns()

resnet50/urls.py
from django.urls import path
from django.conf import settings 
from django.conf.urls.static import static 

from . import views

app_name = 'resnet50'
urlpatterns = [
    path("", views.index, name="index"),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

resnet50/models.py
from django.db import models

# Create your models here.
class Upload(models.Model): 
    image = models.ImageField(upload_to='images/') 

resnet50/forms.py
from django import forms
from .models import Upload

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ['image']
        widgets = {
            'image' : forms.ClearableFileInput(attrs={'class':'custom-file-input'}),
        }

# class UploadFileForm(forms.Form):
#     file = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class':'custom-file-input'}), upload_to='images/');

resnet50/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.conf import settings 

import json
from .forms import UploadFileForm
from .resnet import predict
import os
import glob


# Create your views here.
def index(request):
    prediction = ''
    filename = ''
    if request.method == "POST":
        files = glob.glob('media/images/*')
        for file in files:
            os.remove(file)        

        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            filename = request.FILES['image'].name
            prediction = predict(os.path.join(settings.MEDIA_ROOT, f'images/{filename}'))
        return render(request, "resnet50/index.html", {
            'form' : form,
            'prediction' : prediction,
            'img' : os.path.join(settings.MEDIA_URL, f'images/{filename}'),
        })
    else:
        form = UploadFileForm()
    return render(request, "resnet50/index.html", {
        'form' : form,
        'prediction' : prediction,
        'img' : '',
    })

resnet50/templates/resnet50/index.html
{% extends "resnet50/layout.html" %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block body %}
    <div class="d-flex" style="height:22vh"></div>
    <div class="container">
        <div class="d-flex flex-column align-items-center">

            <div class="p-2">
                <img id="uploaded" src="{{img}}" alt="" />
            </div>

            {% if prediction %}
                <div class="p-2">{{prediction}}</div>
            {% endif %}                      

            <form method="POST" enctype="multipart/form-data" class="p-2">
                {% csrf_token %}
                <div class="custom-file">
                    {% for field in form %}
                        <label class="custom-file-label" for="{{ field.auto_id }}">{{ field.label }}</label>
                        {{field}}
                    {% endfor %}
                    <div class="text-center">
                        <input type="submit" class="btn btn-primary my-2" value="Predict" style="width: 100%;">
                    </div>
                </div>
            </form>

        </div>
    </div>
    <div class="d-flex" style="height:33vh"></div>

{% endblock body %}

{% block scripts %}
    <script>
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                
                reader.onload = function(e) {
                    $('#uploaded').attr('src', e.target.result);
                }
                
                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }

        $("#id_image").change(function() {
            readURL(this);
        });        
    </script>

{% endblock scripts %}

resnet50/templates/resnet50/layout.html
{% load static %}
<!DOCTYPE html> 
<html lang="en">
  <head>
    <title>ResNet 50 Interface</title>
    <script src="{% static 'resnet50/js/jquery-3.5.1.min.js'%}"></script>
    <script src="{% static 'resnet50/js/bootstrap.bundle.min.js'%}" defer></script>
    <link rel="stylesheet" href="{% static 'resnet50/css/bootstrap.min.css'%}"/>
    {% block stylesheets %} 
    {% endblock stylesheets %}
  </head>

  <body>
    {% block body %} 
    {% endblock body %}
  </body>

  {% block scripts %} 
  {% endblock scripts %}
</html>